### ISSUE TITLE
Is this project deprecated? 

### ISSUE THREAD

**Issue by uduse** [Ramblurr/intellij-beancount#6]
I can't download this from the market place anymore.

(edit: maybe this is because I'm using PyCharm?)

**Comment by Ramblurr** [comment]
Thanks for your interest!

It was never published on the market place.

I can't say this project is "deprecated", because it was never supported or published. It was just a side project I worked on for awhile. I don't use Intellij et al any longer, so I've no interest in working on it.

The project is licensed under the GPL v3. Feel free to fork it and improve it yourself.
